# Guitar specifications - this file is updated by the editor
# ─────────────────────────────────────────────────────────────────────────────

GUITARS = [
    {
        "name": "PRS C24",
        "n_strings": 6,
        "scale": 25.0,
        "tuning": ["E4", "B3", "G3", "D3", "A2", "E2"],
        "string_types": None,
        "target_plain": [13.0, 15.5],
        "target_wound": [16.0, 20.0],
    },
    {
        "name": "Charvel DK24",
        "n_strings": 6,
        "scale": 25.5,
        "tuning": ["E4", "B3", "G3", "D3", "A2", "D2"],
        "string_types": None,
        "target_plain": [13.0, 15.5],
        "target_wound": [16.0, 20.0],
    },
    {
        "name": "Padalka Space112",
        "n_strings": 6,
        "scale": 25.5,
        "tuning": ["Eb4", "Bb3", "Gb3", "Db3", "Ab2", "Eb2"],
        "string_types": None,
        "target_plain": [13.0, 15.5],
        "target_wound": [16.0, 20.0],
    },
    {
        "name": "Kiesel Theos",
        "n_strings": 6,
        "scale": 25.5,
        "tuning": ["D4", "A3", "F3", "C3", "G2", "D2"],
        "string_types": None,
        "target_plain": [13.0, 15.5],
        "target_wound": [16.0, 20.0],
    },
    {
        "name": "Padalka Mars",
        "n_strings": 6,
        "scale": 25.5,
        "tuning": ["C#4", "G#3", "E3", "B2", "F#2", "C#2"],
        "string_types": None,
        "target_plain": [13.0, 15.5],
        "target_wound": [16.0, 20.0],
    },
    {
        "name": "Kiesel K-Series",
        "n_strings": 6,
        "scale": 25.5,
        "tuning": ["C4", "G3", "Eb3", "Bb2", "F2", "C2"],
        "string_types": ["p", "p", "w", "w", "w", "w"],
        "target_plain": [13.0, 15.5],
        "target_wound": [16.0, 20.0],
    },
    {
        "name": "Padalka Space155",
        "n_strings": 7,
        "scale": [25.5, 27.0],
        "tuning": ["E4", "B3", "G3", "D3", "A2", "E2", "B1"],
        "string_types": None,
        "target_plain": [13.0, 15.5],
        "target_wound": [16.0, 20.0],
    },
    {
        "name": "Padalka Neptune",
        "n_strings": 7,
        "scale": [26.5, 28.0],
        "tuning": ["D4", "A3", "F3", "C3", "G2", "D2", "A1"],
        "string_types": None,
        "target_plain": [13.0, 15.5],
        "target_wound": [16.0, 20.0],
    },
    {
        "name": "EBMM JP15",
        "n_strings": 7,
        "scale": 25.5,
        "tuning": ["Eb4", "Bb3", "Gb3", "Db3", "Ab2", "Eb2", "Bb1"],
        "string_types": None,
        "target_plain": [13.0, 15.5],
        "target_wound": [16.0, 20.0],
    },
    {
        "name": "Dell'Isola Island",
        "n_strings": 8,
        "scale": 27.0,
        "tuning": ["E4", "B3", "G3", "D3", "A2", "E2", "B1", "F#1"],
        "string_types": None,
        "target_plain": [13.0, 15.5],
        "target_wound": [16.0, 20.0],
    },
]
